# Generated by Django 3.1.5 on 2021-01-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafeteriacore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduserinfo',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
